name: Workflow trigger using Schedule
on: 
  schedule: 
    - cron: "31 4 22 3 *"   # 10:16 AM NPT (04:31 AM UTC)
    - cron: "31 16 22 3 *"  # 10:16 PM NPT (04:31 PM UTC)

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: brush it off!
        run: echo "Reminding you to brush your teeth."
